server:
  port: 8888
spring:
  application:
    name: ead-config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/JadersonCardoso/ead-config-server-repo
          default-label: main
          username: ${GIT_USER_NAME}
          password: ${GIT_PASSWORD}
ead:
  configServer:
    username: ${USER_NAME_CONFIG}
    password: ${PASSWORD_CONFIG}
  serviceRegistry:
    username: ${USER_NAME_REGISTRY}
    password: ${PASSWORD_REGISTRY}

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost
