server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://172.20.217.157:5432/ead-authuser
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect:
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: always

logging:
  level:
    com.ead: TRACE #apenas para o pacote
    root: INFO  #log de toda aplicação, pasta root
    org.springframework.web: DEBUG #mostra os detalhes da requisição
    org.hibernate: INFO
ead:
  api:
    url:
      course: 'http://localhost:8082'