server:
  port: 8082

spring:
  application:
    name: ead-course-service
  datasource:
    url: jdbc:postgresql://172.20.217.157:5432/ead-course
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect:
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: always

logging:
  level:
    com.ead: TRACE
    root: info
    org.springframework.web: DEBUG
    org.hibernate: INFO
ead:
  api:
    url:
      authuser: 'http://localhost:8087'

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost